; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	D:\cpp_prj\day_1\1_function_overloading.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?square@@YAHH@Z					; square
; Function compile flags: /Odtp
; File d:\cpp_prj\day_1\1_function_overloading.cpp
_TEXT	SEGMENT
_a$ = 8							; size = 4
?square@@YAHH@Z PROC					; square

; 8    : int square(int a) {

	push	ebp
	mov	ebp, esp

; 9    : 	return a*a;

	mov	eax, DWORD PTR _a$[ebp]
	imul	eax, DWORD PTR _a$[ebp]

; 10   : }

	pop	ebp
	ret	0
?square@@YAHH@Z ENDP					; square
_TEXT	ENDS
PUBLIC	?square@@YANN@Z					; square
EXTRN	__fltused:DWORD
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 8
?square@@YANN@Z PROC					; square

; 12   : double square(double a) {

	push	ebp
	mov	ebp, esp

; 13   : 	return a*a;

	fld	QWORD PTR _a$[ebp]
	fmul	QWORD PTR _a$[ebp]

; 14   : }

	pop	ebp
	ret	0
?square@@YANN@Z ENDP					; square
_TEXT	ENDS
PUBLIC	__real@400a666666666666
PUBLIC	_main
;	COMDAT __real@400a666666666666
CONST	SEGMENT
__real@400a666666666666 DQ 0400a666666666666r	; 3.3
; Function compile flags: /Odtp
CONST	ENDS
_TEXT	SEGMENT
_main	PROC

; 16   : int main() {

	push	ebp
	mov	ebp, esp

; 17   : 	square(3);

	push	3
	call	?square@@YAHH@Z				; square

; 18   : 	square(3.3);

	add	esp, -4					; fffffffcH
	fld	QWORD PTR __real@400a666666666666
	fstp	QWORD PTR [esp]
	call	?square@@YANN@Z				; square
	fstp	ST(0)
	add	esp, 8

; 19   : }

	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
