#!/bin/bash

# -----------------------------------------------------
export SRC_WORKSPACE=/home/dc.shin/workplace
export SRC_JAM=$SRC_WORKSPACE/test_rep/codejam

alias cda="cd $SRC_JAM"
alias cdw="cd $SRC_WORKSPACE"

List=(
$SRC_JAM/2011_qround
$SRC_JAM/2010_africa_online
$SRC_JAM/2010_africa_qround
/cygdrive/x/workplace/batman_vzw_us/android/out/target/product/batman_vzw
)

# -----------------------------------------------------

function c() 
{
    i=0
    len=${#List[*]}
    while [ $i -lt $len ] ; do
        echo "$i :${List[$i]}"
        let i++
    done
    
    read Target
    if [ $Target -ge $len ] ; then
        echo "out of range: length $len"
    else
        #echo "$SRC_HOME/${List[$Target]}"
        cd ${List[$Target]}
        pwd
    fi
}

cd $SRC_JAM
echo "Home Directory: $SRC_JAM"
